### ISSUE TITLE
Set up Social Media

### ISSUE THREAD

**Issue by Erin-Denton** [cforlando/NDoCH-Planning#18]
Set up your social media hashtag a few weeks before your event. For CodeAcross, we use the #codeacross hashtag and for National Day of Civic Hacking we use #hackforchange. If you have your own hashtag that you use for your regular Brigade meetups - you can use that too.

Tweeting and posting throughout the day will help encourage other people in the community as well as help set up a timeline of events. This will make it easier to blog about your event later.

**Comment by dridenour** [comment]
Working on this now. I have the person in mind and I will prep her on everything

**Comment by Erin-Denton** [comment]
official social tags:
#hackforchange
#hackfororlando
