### ISSUE TITLE
Reach out to the Press

### ISSUE THREAD

**Issue by Erin-Denton** [cforlando/NDoCH-Planning#19]
Reaching out to the press can be a great way to attract people to the event and to help tell your story after the event. Check out the Brigade Organizer playbook for tips on interacting with the press or tag the Brigade team in Slack.

**Comment by Erin-Denton** [comment]
Orlando Sentinel (Marco Santana) -andrew will reachout
wmfenews@wmfe.org

**Comment by akozlik** [comment]
I've reached out to both WMFE and the Orlando Sentinel.
