### ISSUE TITLE
Get Volunteers to Help Andrew

### ISSUE THREAD

**Issue by Erin-Denton** [cforlando/NDoCH-Planning#23]
Current:
Day of Operations: Shanika Marlow

Need:
Social Media and photography/video
Sign in table 
Set up/Break down & cleaning of event

All volunteers will receive: 
-A Code for Orlando Shirt, stickers, free breakfast and coffee, lunch and drinks.

**Comment by Erin-Denton** [comment]
Shanika Marlow says she will be there to help with some operational tasks.

**Comment by Erin-Denton** [comment]
-Ask Katlyn in Odevs about volunteer help after final meetup description is live with sign up info

**Comment by dridenour** [comment]
I have asked for the volunteers! I will get as much detail as possible

**Comment by Erin-Denton** [comment]
Currently setting date for Orientation
