### ISSUE TITLE
Secure $$ Sponsors

### ISSUE THREAD

**Issue by Erin-Denton** [cforlando/NDoCH-Planning#8]

**Comment by Erin-Denton** [comment]
We need sponsors for food:

Breakfast
Coffee
Lunch
Drinks (water, soda etc)

Optional: BEER ??

**Comment by chadmiller** [comment]
How much do we need?  ~$12 per person? About 100 people?

**Comment by Erin-Denton** [comment]
Andrew is handling this one, I know he is talking to a sponsor now that might be able to cover it all so we will have to wait and see what they say. Do you know a potential sponsor we should throw into consideration?

**Comment by chadmiller** [comment]
I was going to ask my employer.

On Tue, May 10, 2016 at 10:46 AM, Erin Denton notifications@github.com
wrote:

> Andrew is handling this one, I know he is talking to a sponsor now that
> might be able to cover it all so we will have to wait and see what they
> say. Do you know a potential sponsor we should throw into consideration?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/cforlando/NDoCH-Planning/issues/8#issuecomment-218180392

## 

Chad Miller
chad.org
c2c3 0e6c a4ce d49e 79cf   06c61 a806 deac 3042 0066
